name: Application

on:
  pull_request:
    branches: [main, master]
    paths:
      - "app/**"
      - "deploy/app/**"
      - ".github/workflows/app.yaml"
  push:
    branches: [main, master]
    paths:
      - "app/**"
      - "deploy/app/**"
      - ".github/workflows/app.yaml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build_push:
    name: Build and push ${{ matrix.environment }} image
    strategy:
      fail-fast: true
      matrix:
        stack: [app]
        environment:
    uses: tx-pts-dai/github-workflows/.github/workflows/docker-build-push-ecr.yaml@v2
    with:
      docker_context: "."
      dockerfile_path: "./Dockerfile"
      image_name: ""
      environment: ${{ matrix.stack }}-${{ matrix.environment }}

  deploy_feature:
    if: github.event_name == 'pull_request'
    name: Deploy feature branch
    needs: [build_push]
    strategy:
      matrix:
        stack: [app]
        environment: ['dev']
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-feature.yaml@v2
    with:
      tf_vars: |
        branch="${{ github.head_ref }}"
        image_tag="${{ github.sha }}"
      tf_workspace: ${{ github.head_ref }}
      environment: ${{ matrix.stack }}-${{ matrix.environment }}

  plan:
    if: github.event_name == 'pull_request'
    name: Plan ${{ matrix.environment }}
    needs: [build_push]
    strategy:
      fail-fast: false
      matrix:
        stack: [app]
        environment:
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-plan.yaml@v2
    with:
      tf_vars: |
        image_tag="${{ github.sha }}"
      environment: ${{ matrix.stack }}-${{ matrix.environment }}

  apply:
    if: github.ref_name == github.event.repository.default_branch && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    name: Deploy ${{ matrix.environment }}
    needs: [build_push]
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        stack: [app]
        environment:
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-apply.yaml@v2
    with:
      tf_vars: |
        image_tag="${{ github.sha }}"
      environment: ${{ matrix.stack }}-${{ matrix.environment }}
