apiVersion: apps/v1
kind: Deployment
metadata:
  name: @{{ cookiecutter.service_name }}
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: @{{ cookiecutter.service_name }}
  template:
    metadata:
    spec:
      containers:
        - name: @{{ cookiecutter.service_name }}
          image: @{{ cookiecutter.ecr_aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/@{{ cookiecutter.service_name }}:dev-fe0876a-1634820169
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: svcport
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
              cpu: "20m"
            limits:
              memory: "200Mi"
