---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: @{{ cookiecutter.service_name }}
  namespace: flux-system
spec:
  provider: aws # Automatic authentication if the IAM role is allowed to read from ECR
  image: @{{ cookeiecutter.ecr_aws_accoun_id }}.dkr.ecr.eu-west-1.amazonaws.com/@{{ cookiecutter.service_name }} # Prod ECR repsitory
  interval: 1m0s
