apiVersion: apps/v1
kind: Deployment
metadata:
  name: @{{ service_name }}
spec:
  template:
    spec:
      containers:
        - name: @{{ service_name }}
          image: @{{ ecr_aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/@{{ service_name }}:1.0.0 # {"$imagepolicy": "flux-system:prod-@{{ service_name }}"}
          envFrom:
            - secretRef:
                name: @{{ service_name }}-env-dev
      imagePullSecrets:
        - name: regcred-dev
