apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: @{{ service_name }}
spec:
  rules:
    - host: @{{ service_name }}-dev.sfmc-dev.tx.group
      http:
        paths:
          - backend:
              service:
                name: @{{ service_name }}-dev
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific

  tls:
    - hosts:
        - @{{ service_name }}-dev.sfmc-dev.tx.group
