apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/@{{ service_name }}
  # - app-SealedSecret-env.yaml
namespace: dev
nameSuffix: -dev
replicas:
  - name: @{{ service_name }}-dev
    count: 1
commonLabels:
  app: @{{ service_name }}-dev
commonAnnotations:
  reloader.stakater.com/auto: "true"
patchesStrategicMerge:
  - app-Deployment.yaml
  - app-IngressRule.yaml
