apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: prod-@{{ service_name }}
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: @{{ service_name }}
  policy:
    semver:
      range: <=2.0.0
