---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: @{{ service_name }}
  namespace: flux-system
spec:
  provider: aws # Automatic authentication if the IAM role is allowed to read from ECR
  image: @{{ ecr_aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/@{{ service_name }} # Prod ECR repsitory
  interval: 1m0s
