on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cookiecutter --no-input --directory bases/simple-app --output-dir test/simple-app . github_repo=simple-app-repo github_org=tx-pts-dai
          cookiecutter --no-input --directory bases/sfmc-app --output-dir test/sfmc-app . github_repo=sfmc-app-repo github_org=dnd-it
          cookiecutter --no-input --directory addons/mkdocs --output-dir test/mkdocs . github_repo=mkdocs-repo github_org=tx-group-adm
          cookiecutter --no-input --directory addons/flux-cronjob-deployment --output-dir test/flux-cronjob-deployment . github_repo=flux-cronjob-repo github_org=tx-pts-dai
          cookiecutter --no-input --directory addons/flux-service-deployment --output-dir test/flux-service-deployment . github_repo=flux-service-repo github_org=dnd-it
          cookiecutter --no-input --directory addons/github-workflows --output-dir test/github-workflows . github_repo=github-workflows-repo github_org=tx-group-adm
          cookiecutter --no-input --directory addons/discovery-app-layer --output-dir test/discovery-app . github_repo=discovery-app-repo github_org=tx-group-adm
