on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cookiecutter --no-input --directory bases/simple-app .
          cookiecutter --no-input --directory bases/sfmc-app .
          cookiecutter --no-input --directory addons/mkdocs .
          cookiecutter --no-input --directory addons/flux-cronjob-deployment .
          cookiecutter --no-input --directory addons/flux-service-deployment .
